# Generated by Django 4.0.6 on 2022-08-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0003_task_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
