# Generated by Django 4.0.6 on 2022-08-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0005_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='deadline',
        ),
    ]
